// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleCamera
        {
            get
            {
                return SteamVR_Actions.default_ToggleCamera;
            }
        }
        
        public virtual SteamVR_Action_Boolean Record
        {
            get
            {
                return SteamVR_Actions.default_Record;
            }
        }
        
        public virtual SteamVR_Action_Boolean PanTrigger
        {
            get
            {
                return SteamVR_Actions.default_PanTrigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Orient
        {
            get
            {
                return SteamVR_Actions.default_Orient;
            }
        }
        
        public virtual SteamVR_Action_Boolean Laser
        {
            get
            {
                return SteamVR_Actions.default_Laser;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Zoom
        {
            get
            {
                return SteamVR_Actions.default_Zoom;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlayPause
        {
            get
            {
                return SteamVR_Actions.default_PlayPause;
            }
        }
        
        public virtual SteamVR_Action_Boolean Playback
        {
            get
            {
                return SteamVR_Actions.default_Playback;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
